[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Vardan <vardan_p@instigatemobile.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
